ROOT_DIR = ''
KNOWN_NODES_DIR = ROOT_DIR+'memory/know_nodes.json'
MEMPOOL_DIR = ROOT_DIR+'memory/mempool.json'
BLOCKCHAIN_DIR = ROOT_DIR+'memory/blockchain.json'
TARGET_HASH_CONF_DIR = ROOT_DIR+'memory/target_hash_config.json'
E_CERT_SYS_HOSTNAME = '127.0.0.1:8000'
MY_HOSTNAME = '127.0.0.1:8003'
FIRST_KNOW_NODE_HOSTNAME = '127.0.0.1:8003'